// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartApartment.Persistence;

namespace SmartApartment.NetCoreApp.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210804124002_ApartmentInfoMigration")]
    partial class ApartmentInfoMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("SmartApartment.Domain.Entities.Apartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ApartmentTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentTypeId");

                    b.ToTable("Apartments");
                });

            modelBuilder.Entity("SmartApartment.Domain.Entities.ApartmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ApartmentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(2029),
                            Name = "Duplex"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(3016),
                            Name = "Triplex"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(3064),
                            Name = "Quadruplex"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(3067),
                            Name = "Loft"
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(3070),
                            Name = "Micro Apartment"
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(3078),
                            Name = "Studio"
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(3081),
                            Name = "High-rise"
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(3083),
                            Name = "Mid-rise"
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(3086),
                            Name = "Walk-up"
                        },
                        new
                        {
                            Id = 10,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(3091),
                            Name = "Condo"
                        },
                        new
                        {
                            Id = 11,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(3094),
                            Name = "Townhouse"
                        });
                });

            modelBuilder.Entity("SmartApartment.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 776, DateTimeKind.Local).AddTicks(9251),
                            Name = "Birmingham",
                            StateId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(982),
                            Name = "Hunstville",
                            StateId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1052),
                            Name = "Mobile",
                            StateId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1056),
                            Name = "Montgomery",
                            StateId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1060),
                            Name = "Flagstaff",
                            StateId = 2
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1070),
                            Name = "Phoenix",
                            StateId = 2
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1074),
                            Name = "Tucson",
                            StateId = 2
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1077),
                            Name = "Central Coast",
                            StateId = 3
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1080),
                            Name = "San Joaquin Valley",
                            StateId = 3
                        },
                        new
                        {
                            Id = 10,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1086),
                            Name = "Inland Empire",
                            StateId = 3
                        },
                        new
                        {
                            Id = 11,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1089),
                            Name = "Los Angeles",
                            StateId = 3
                        },
                        new
                        {
                            Id = 12,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1092),
                            Name = "San Francisco",
                            StateId = 3
                        },
                        new
                        {
                            Id = 13,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1095),
                            Name = "Orange County",
                            StateId = 3
                        },
                        new
                        {
                            Id = 14,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1098),
                            Name = "Sacramento",
                            StateId = 3
                        },
                        new
                        {
                            Id = 15,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1103),
                            Name = "San Diego",
                            StateId = 3
                        },
                        new
                        {
                            Id = 16,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1106),
                            Name = "Bay Area/San Francisco",
                            StateId = 3
                        },
                        new
                        {
                            Id = 17,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1109),
                            Name = "Denver",
                            StateId = 4
                        },
                        new
                        {
                            Id = 18,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1116),
                            Name = "Colorado Springs",
                            StateId = 4
                        },
                        new
                        {
                            Id = 19,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1120),
                            Name = "Fairfield County",
                            StateId = 5
                        },
                        new
                        {
                            Id = 20,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1123),
                            Name = "Hartford",
                            StateId = 5
                        },
                        new
                        {
                            Id = 21,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1126),
                            Name = "Middlesex County",
                            StateId = 5
                        },
                        new
                        {
                            Id = 22,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1129),
                            Name = "New Haven County",
                            StateId = 5
                        },
                        new
                        {
                            Id = 23,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1133),
                            Name = "Tolland County",
                            StateId = 5
                        },
                        new
                        {
                            Id = 24,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1135),
                            Name = "Washington D.C.",
                            StateId = 6
                        },
                        new
                        {
                            Id = 25,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1138),
                            Name = "Southwest Florida",
                            StateId = 7
                        },
                        new
                        {
                            Id = 26,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1141),
                            Name = "Northwest Florida",
                            StateId = 7
                        },
                        new
                        {
                            Id = 27,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1144),
                            Name = "Melbourne & Palm Bay",
                            StateId = 7
                        },
                        new
                        {
                            Id = 28,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1147),
                            Name = "Palm Beach & Boca",
                            StateId = 7
                        },
                        new
                        {
                            Id = 29,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1150),
                            Name = "Jacksonville",
                            StateId = 7
                        },
                        new
                        {
                            Id = 30,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1153),
                            Name = "Gainesville",
                            StateId = 7
                        },
                        new
                        {
                            Id = 31,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1156),
                            Name = "Miami/Ft. Lauderdale",
                            StateId = 7
                        },
                        new
                        {
                            Id = 32,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1159),
                            Name = "Tampa",
                            StateId = 7
                        },
                        new
                        {
                            Id = 33,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1162),
                            Name = "Orlando",
                            StateId = 7
                        },
                        new
                        {
                            Id = 34,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1168),
                            Name = "Albany",
                            StateId = 8
                        },
                        new
                        {
                            Id = 35,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1171),
                            Name = "Atlanta",
                            StateId = 8
                        },
                        new
                        {
                            Id = 36,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1174),
                            Name = "Macon",
                            StateId = 8
                        },
                        new
                        {
                            Id = 37,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1176),
                            Name = "Augusta",
                            StateId = 8
                        },
                        new
                        {
                            Id = 38,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1179),
                            Name = "Savannah",
                            StateId = 8
                        },
                        new
                        {
                            Id = 39,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1182),
                            Name = "Chicago",
                            StateId = 9
                        },
                        new
                        {
                            Id = 40,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1185),
                            Name = "Moline",
                            StateId = 9
                        },
                        new
                        {
                            Id = 41,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1188),
                            Name = "Springfield",
                            StateId = 9
                        },
                        new
                        {
                            Id = 42,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1190),
                            Name = "Evansville",
                            StateId = 10
                        },
                        new
                        {
                            Id = 43,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1193),
                            Name = "Fort Wayne",
                            StateId = 10
                        },
                        new
                        {
                            Id = 44,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1196),
                            Name = "Indianapolis",
                            StateId = 10
                        },
                        new
                        {
                            Id = 45,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1199),
                            Name = "South Bend/Mishawaka",
                            StateId = 10
                        },
                        new
                        {
                            Id = 46,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1203),
                            Name = "Davenport",
                            StateId = 11
                        },
                        new
                        {
                            Id = 47,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1206),
                            Name = "Des Moines",
                            StateId = 11
                        },
                        new
                        {
                            Id = 48,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1208),
                            Name = "Sioux City",
                            StateId = 11
                        },
                        new
                        {
                            Id = 49,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1211),
                            Name = "DFW",
                            StateId = 12
                        },
                        new
                        {
                            Id = 50,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1214),
                            Name = "Tyler",
                            StateId = 12
                        },
                        new
                        {
                            Id = 51,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1217),
                            Name = "Longview",
                            StateId = 12
                        },
                        new
                        {
                            Id = 52,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1219),
                            Name = "Houston",
                            StateId = 12
                        },
                        new
                        {
                            Id = 53,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1222),
                            Name = "Victoria",
                            StateId = 12
                        },
                        new
                        {
                            Id = 54,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1225),
                            Name = "Corpus Christi",
                            StateId = 12
                        },
                        new
                        {
                            Id = 55,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1228),
                            Name = "Golden Triangle",
                            StateId = 12
                        },
                        new
                        {
                            Id = 56,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1231),
                            Name = "Lufkin",
                            StateId = 12
                        },
                        new
                        {
                            Id = 57,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1233),
                            Name = "Austin",
                            StateId = 12
                        },
                        new
                        {
                            Id = 58,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1236),
                            Name = "San Antonio",
                            StateId = 12
                        },
                        new
                        {
                            Id = 59,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1239),
                            Name = "I-35 Corridor",
                            StateId = 12
                        },
                        new
                        {
                            Id = 60,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1242),
                            Name = "College Station",
                            StateId = 12
                        },
                        new
                        {
                            Id = 61,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1245),
                            Name = "Abilene",
                            StateId = 12
                        },
                        new
                        {
                            Id = 62,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1251),
                            Name = "Amarillo",
                            StateId = 12
                        },
                        new
                        {
                            Id = 63,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1253),
                            Name = "Midland/Odessa",
                            StateId = 12
                        },
                        new
                        {
                            Id = 64,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1255),
                            Name = "Lubbock",
                            StateId = 12
                        },
                        new
                        {
                            Id = 65,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1258),
                            Name = "Laredo",
                            StateId = 12
                        },
                        new
                        {
                            Id = 66,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1263),
                            Name = "Harlingen",
                            StateId = 12
                        },
                        new
                        {
                            Id = 67,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 777, DateTimeKind.Local).AddTicks(1265),
                            Name = "Wichita Falls",
                            StateId = 12
                        });
                });

            modelBuilder.Entity("SmartApartment.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Barcode")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SmartApartment.Domain.Entities.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 772, DateTimeKind.Local).AddTicks(7719),
                            Name = "Alabama"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 776, DateTimeKind.Local).AddTicks(8274),
                            Name = "Arizona"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 776, DateTimeKind.Local).AddTicks(8336),
                            Name = "California"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 776, DateTimeKind.Local).AddTicks(8340),
                            Name = "Colorado"
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 776, DateTimeKind.Local).AddTicks(8402),
                            Name = "Connecticut"
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 776, DateTimeKind.Local).AddTicks(8412),
                            Name = "District of Columbia"
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 776, DateTimeKind.Local).AddTicks(8414),
                            Name = "Florida"
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 776, DateTimeKind.Local).AddTicks(8416),
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 776, DateTimeKind.Local).AddTicks(8418),
                            Name = "Illiois"
                        },
                        new
                        {
                            Id = 10,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 776, DateTimeKind.Local).AddTicks(8422),
                            Name = "Indiana"
                        },
                        new
                        {
                            Id = 11,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 776, DateTimeKind.Local).AddTicks(8424),
                            Name = "Iowa"
                        },
                        new
                        {
                            Id = 12,
                            CreatedOn = new DateTime(2021, 8, 4, 13, 40, 1, 776, DateTimeKind.Local).AddTicks(8426),
                            Name = "Texas"
                        });
                });

            modelBuilder.Entity("SmartApartment.Domain.Entities.Apartment", b =>
                {
                    b.HasOne("SmartApartment.Domain.Entities.ApartmentType", "ApartmentType")
                        .WithMany("Apartments")
                        .HasForeignKey("ApartmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApartmentType");
                });

            modelBuilder.Entity("SmartApartment.Domain.Entities.ApartmentType", b =>
                {
                    b.Navigation("Apartments");
                });
#pragma warning restore 612, 618
        }
    }
}
